apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns.yaml
  - configmap.yaml
  - pvc.yaml
  - chroma.yaml
  - rabbitmq.yaml
  - api.yaml
  - ui-search.yaml
  - ui-speaker.yaml
  - ingestion-worker.yaml
  - ingress.yaml
